name: Origin Rewind
favicon: null
layout_spectrum: 1
typography_spectrum: 0.06934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.16653614299540243
  lightness: 0.04532686728755153
  saturation: 0.8232964154153689
  rhythmicContrast: 0.7596469256609621
purpose:
  - name: null
    item: null
    url: null
