name: Origin Rewind
favicon: null
layout_spectrum: 1
typography_spectrum: 0.03868
title: Origin Rewind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
